const modules=window.MODULES;let chapter=0,current=null,state={};try{state=JSON.parse(localStorage.getItem("bush123")||"{}")}catch(e){}
const CH={1:["CAPITOLUL I","Importanța leadershipului și a managementului educațional","0003.gif","0004.gif"],2:["CAPITOLUL II","Modele de leadership și management educațional","0005.gif","0006.gif"],3:["CAPITOLUL III","Modelele formale","0007.gif","0008.gif"]};
function k(m,q){return m.id+":"+q}function save(){localStorage.setItem("bush123",JSON.stringify(state))}
function chooseChapter(c){chapter=c;let sb=document.querySelector('.tabs button[data-tab="scheme"]');if(sb)sb.textContent=c===3?"🧠 Hartă interactivă":"⌘ Scheme";document.getElementById("home").classList.add("hidden");document.getElementById("study").classList.remove("hidden");document.getElementById("chapterLabel").textContent=CH[c][0];document.getElementById("chapterTitle").textContent=CH[c][1];document.getElementById("chapterHead").innerHTML='<div class="head-pair"><img src="'+CH[c][2]+'"><img src="'+CH[c][3]+'"></div><b>'+CH[c][0]+'</b><span>'+CH[c][1]+'</span>';buildMenu();let ms=modules.filter(m=>m.id.startsWith(c+"."));if(ms.length)openModule(modules.indexOf(ms[0]))}
function goHome(){document.getElementById("study").classList.add("hidden");document.getElementById("home").classList.remove("hidden");window.scrollTo(0,0)}
function buildMenu(){let box=document.getElementById("moduleList");box.innerHTML="";modules.forEach((m,i)=>{if(!m.id.startsWith(chapter+"."))return;let a=0;m.questions.forEach((q,j)=>{if(Number.isInteger(state[k(m,j)]))a++});let b=document.createElement("button");b.className="navitem"+(i===current?" active":"");b.innerHTML='<strong>'+m.id+'</strong><span>'+m.title+'</span><em>'+a+'/'+m.questions.length+'</em>';b.onclick=()=>openModule(i);box.appendChild(b)});updateProgress()}
function updateProgress(){let ms=modules.filter(m=>m.id.startsWith(chapter+".")),tot=0,ans=0;ms.forEach(m=>m.questions.forEach((q,j)=>{tot++;if(Number.isInteger(state[k(m,j)]))ans++}));let p=tot?Math.round(ans/tot*100):0;document.getElementById("progressText").textContent=ans+" / "+tot+" · "+p+"%";document.getElementById("progressBar").style.width=p+"%"}
function openModule(i){current=i;let m=modules[i];document.getElementById("moduleCode").textContent="SECȚIUNEA "+m.id;document.getElementById("moduleTitle").textContent=m.title;document.getElementById("audioPlayer").src=m.audio||"";showTab("audio");renderQuiz();buildMenu();window.scrollTo({top:150,behavior:"smooth"})}
function showTab(tab){let m=modules[current],L=(window.LEARNING||{})[m.id]||{ideas:["Material de fixare în curs de completare."],formula:"",scheme:[]};document.querySelectorAll(".tabs button").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));document.getElementById("audioPane").classList.toggle("hidden",tab!=="audio");document.getElementById("ideasPane").classList.toggle("hidden",tab!=="ideas");document.getElementById("schemePane").classList.toggle("hidden",tab!=="scheme");if(tab==="ideas"){document.getElementById("ideasPane").innerHTML='<div class="learnbox"><h4>💡 Idei esențiale</h4><ul>'+L.ideas.map(x=>'<li>'+x+'</li>').join("")+'</ul>'+(L.formula?'<div class="formula"><b>De reținut:</b> '+L.formula+'</div>':"")+'</div>'}if(tab==="scheme"){if(chapter===3){renderFormalMap()}else{document.getElementById("schemePane").innerHTML='<div class="learnbox"><h4>⌘ Schema de memorare</h4><div class="schemeflow">'+L.scheme.map((x,j)=>'<div class="schemeitem">'+x+'</div>'+(j<L.scheme.length-1?'<div class="arrow">↓</div>':"")).join("")+'</div>'+(L.formula?'<div class="formula"><b>Formula:</b> '+L.formula+'</div>':"")+'</div>'}}}
function renderQuiz(){let m=modules[current],box=document.getElementById("quiz");box.innerHTML="";let answered=0;m.questions.forEach((q,qi)=>{let chosen=state[k(m,qi)];if(Number.isInteger(chosen))answered++;let card=document.createElement("section");card.className="question";card.innerHTML='<div class="qtitle"><b>?</b><span>Întrebarea '+(qi+1)+'</span></div><h4>'+q.q+'</h4>';let ops=document.createElement("div");ops.className="options";let arr=q.options.map((t,orig)=>({t,orig})).sort((x,y)=>x.t.localeCompare(y.t,"ro",{sensitivity:"base"}));arr.forEach((x,di)=>{let bt=document.createElement("button");bt.className="option";bt.innerHTML='<strong>'+String.fromCharCode(97+di)+'.</strong><span>'+x.t+'</span>';if(Number.isInteger(chosen)){bt.disabled=true;if(x.orig===q.answer)bt.classList.add("correct");if(x.orig===chosen&&chosen!==q.answer)bt.classList.add("wrong")}else bt.onclick=()=>{state[k(m,qi)]=x.orig;save();renderQuiz();buildMenu()};ops.appendChild(bt)});card.appendChild(ops);if(Number.isInteger(chosen)){let f=document.createElement("div");f.className="feedback";f.innerHTML='<b>'+(chosen===q.answer?"Corect.":"Răspuns incorect.")+'</b> '+q.feedback;card.appendChild(f)}box.appendChild(card)});document.getElementById("questionCounter").textContent=answered+" din "+m.questions.length+" rezolvați";updateProgress()}

const FORMAL_MAP=[
 {icon:"🎯",name:"OBIECTIVE",q:"Ce vrem să realizăm?",details:["clare și oficiale","orientează deciziile","permit evaluarea rezultatelor"],links:["3.4 Modelele raționale","3.6.1 Obiective"]},
 {icon:"🧱",name:"STRUCTURĂ",q:"Cum ne organizăm?",details:["roluri și poziții","diviziunea muncii","coordonare","organigramă","relații formale"],links:["3.1 Modelele structurale","3.6.2 Structura organizațională"]},
 {icon:"👤",name:"AUTORITATE",q:"Cine decide?",details:["ierarhie","poziție formală","responsabilitate","raportare"],links:["3.3 Modelele birocratice","3.3.1 Birocrația în educație","3.5 Modelele ierarhice"]},
 {icon:"⚙️",name:"FUNCȚIONARE",q:"Cum lucrăm?",details:["reguli și proceduri","decizie rațională","coordonare","control și evaluare"],links:["3.2 Modelele sistemice","3.2.1 Sisteme deschise sau închise","3.6.3 Mediul extern"]},
 {icon:"📊",name:"REZULTATE",q:"Ce obținem?",details:["atingerea obiectivelor","eficacitate","feedback și ajustare"],links:["3.6.4 Leadership","3.7 Leadershipul managerial","3.8 Limitările modelelor formale","3.9 Concluzie"]}
];
function renderFormalMap(){
 let box=document.getElementById("schemePane");
 box.innerHTML='<div class="formalmap"><div class="maptop"><div><small>HARTA CAPITOLULUI III</small><h4>🏫 ȘCOALA CA ORGANIZAȚIE FORMALĂ</h4><p>Pornește de la cele 5 repere. Apasă pe fiecare pentru a reconstrui capitolul.</p></div><button class="visualtest" onclick="startVisualTest()">🧠 Testează-mă vizual</button></div><div class="mapline">'+FORMAL_MAP.map((x,i)=>'<button class="mapnode" onclick="toggleMapNode('+i+',this)"><span class="mapnum">'+(i+1)+'</span><b>'+x.icon+' '+x.name+'</b><small>'+x.q+'</small><em>Apasă pentru detalii ↓</em></button>').join('<span class="maparrow">→</span>')+'</div><div id="mapDetail" class="mapdetail"><b>Alege un element din schemă.</b></div><div class="feedbackloop">↶ FEEDBACK ȘI AJUSTARE — contextul influențează toate elementele ↷</div><div class="maplinks"><h5>Cum derivă subcapitolele din această hartă?</h5>'+FORMAL_MAP.map((x,i)=>'<div><strong>'+(i+1)+'. '+x.name+'</strong><span>'+x.links.join(" • ")+'</span></div>').join("")+'</div></div>';
}
function toggleMapNode(i,el){
 document.querySelectorAll(".mapnode").forEach(x=>x.classList.remove("open"));el.classList.add("open");
 let x=FORMAL_MAP[i];document.getElementById("mapDetail").innerHTML='<div class="detailicon">'+x.icon+'</div><div><h5>'+x.name+' — '+x.q+'</h5><ul>'+x.details.map(d=>'<li>'+d+'</li>').join("")+'</ul><p><b>Legături în capitol:</b> '+x.links.join(" • ")+'</p></div>';
}
function startVisualTest(){
 let box=document.getElementById("schemePane"), order=[...FORMAL_MAP.keys()].sort(()=>Math.random()-.5), missing=order.slice(0,2);
 box.innerHTML='<div class="formalmap testmode"><div class="maptop"><div><small>ACTIVE RECALL</small><h4>🧠 Completează harta din memorie</h4><p>Două repere au dispărut. Alege denumirea corectă pentru fiecare.</p></div><button class="visualtest secondary" onclick="renderFormalMap()">← Înapoi la hartă</button></div><div class="mapline">'+FORMAL_MAP.map((x,i)=>missing.includes(i)?'<div class="mapnode missing" id="miss'+i+'"><span class="mapnum">'+(i+1)+'</span><b>❓</b><select onchange="checkVisual('+i+',this)"><option value="">Alege...</option>'+FORMAL_MAP.map(y=>'<option>'+y.name+'</option>').join("")+'</select></div>':'<div class="mapnode fixed"><span class="mapnum">'+(i+1)+'</span><b>'+x.icon+' '+x.name+'</b><small>'+x.q+'</small></div>').join('<span class="maparrow">→</span>')+'</div><div id="visualResult" class="mapdetail"><b>Reconstituie cele două elemente lipsă.</b></div></div>';
}
function checkVisual(i,sel){
 let ok=sel.value===FORMAL_MAP[i].name, card=document.getElementById("miss"+i);
 card.classList.remove("good","bad");card.classList.add(ok?"good":"bad");
 document.getElementById("visualResult").innerHTML=ok?'<b>Corect:</b> '+FORMAL_MAP[i].icon+' '+FORMAL_MAP[i].name+' — '+FORMAL_MAP[i].q:'<b>Mai încearcă.</b> Gândește-te la ordinea: Obiective → Structură → Autoritate → Funcționare → Rezultate.';
}