const modules=window.MODULES;let chapter=0,current=null,state={};try{state=JSON.parse(localStorage.getItem("bush123")||"{}")}catch(e){}
const CH={1:["CAPITOLUL I","Importanța leadershipului și a managementului educațional","0003.gif","0004.gif"],2:["CAPITOLUL II","Modele de leadership și management educațional","0005.gif","0006.gif"],3:["CAPITOLUL III","Modelele formale","0007.gif","0008.gif"]};
function k(m,q){return m.id+":"+q}function save(){localStorage.setItem("bush123",JSON.stringify(state))}
function chooseChapter(c){chapter=c;document.getElementById("home").classList.add("hidden");document.getElementById("study").classList.remove("hidden");document.getElementById("chapterLabel").textContent=CH[c][0];document.getElementById("chapterTitle").textContent=CH[c][1];document.getElementById("chapterHead").innerHTML='<div class="head-pair"><img src="'+CH[c][2]+'"><img src="'+CH[c][3]+'"></div><b>'+CH[c][0]+'</b><span>'+CH[c][1]+'</span>';buildMenu();let ms=modules.filter(m=>m.id.startsWith(c+"."));if(ms.length)openModule(modules.indexOf(ms[0]))}
function goHome(){document.getElementById("study").classList.add("hidden");document.getElementById("home").classList.remove("hidden");window.scrollTo(0,0)}
function buildMenu(){let box=document.getElementById("moduleList");box.innerHTML="";modules.forEach((m,i)=>{if(!m.id.startsWith(chapter+"."))return;let a=0;m.questions.forEach((q,j)=>{if(Number.isInteger(state[k(m,j)]))a++});let b=document.createElement("button");b.className="navitem"+(i===current?" active":"");b.innerHTML='<strong>'+m.id+'</strong><span>'+m.title+'</span><em>'+a+'/'+m.questions.length+'</em>';b.onclick=()=>openModule(i);box.appendChild(b)});updateProgress()}
function updateProgress(){let ms=modules.filter(m=>m.id.startsWith(chapter+".")),tot=0,ans=0;ms.forEach(m=>m.questions.forEach((q,j)=>{tot++;if(Number.isInteger(state[k(m,j)]))ans++}));let p=tot?Math.round(ans/tot*100):0;document.getElementById("progressText").textContent=ans+" / "+tot+" · "+p+"%";document.getElementById("progressBar").style.width=p+"%"}
function openModule(i){current=i;let m=modules[i];document.getElementById("moduleCode").textContent="SECȚIUNEA "+m.id;document.getElementById("moduleTitle").textContent=m.title;document.getElementById("audioPlayer").src=m.audio||"";renderQuiz();buildMenu();window.scrollTo({top:150,behavior:"smooth"})}
function renderQuiz(){let m=modules[current],box=document.getElementById("quiz");box.innerHTML="";let answered=0;m.questions.forEach((q,qi)=>{let chosen=state[k(m,qi)];if(Number.isInteger(chosen))answered++;let card=document.createElement("section");card.className="question";card.innerHTML='<div class="qtitle"><b>?</b><span>Întrebarea '+(qi+1)+'</span></div><h4>'+q.q+'</h4>';let ops=document.createElement("div");ops.className="options";let arr=q.options.map((t,orig)=>({t,orig})).sort((x,y)=>x.t.localeCompare(y.t,"ro",{sensitivity:"base"}));arr.forEach((x,di)=>{let bt=document.createElement("button");bt.className="option";bt.innerHTML='<strong>'+String.fromCharCode(97+di)+'.</strong><span>'+x.t+'</span>';if(Number.isInteger(chosen)){bt.disabled=true;if(x.orig===q.answer)bt.classList.add("correct");if(x.orig===chosen&&chosen!==q.answer)bt.classList.add("wrong")}else bt.onclick=()=>{state[k(m,qi)]=x.orig;save();renderQuiz();buildMenu()};ops.appendChild(bt)});card.appendChild(ops);if(Number.isInteger(chosen)){let f=document.createElement("div");f.className="feedback";f.innerHTML='<b>'+(chosen===q.answer?"Corect.":"Răspuns incorect.")+'</b> '+q.feedback;card.appendChild(f)}box.appendChild(card)});document.getElementById("questionCounter").textContent=answered+" din "+m.questions.length+" rezolvați";updateProgress()}
