(function(){
function Q(q,correct,wrong,fb){return {q:q,options:[correct].concat(wrong),answer:0,feedback:fb,kind:"Antrenament"}}
function make(id,title,audio,facts){
 let qs=[]; facts.forEach((f,i)=>{qs.push(Q("Care afirmație este corectă despre "+f[0]+"?",f[1],f[2],f[3]));});
 facts.forEach((f,i)=>{qs.push(Q("În logica lui Tony Bush, "+f[0]+" se recunoaște cel mai bine prin:",f[1],f[2].slice().reverse(),f[3]));});
 while(qs.length<10){let f=facts[qs.length%facts.length];qs.push(Q("Alege formularea care păstrează sensul conceptului „"+f[0]+"”:",f[1],f[2],f[3]));}
 return {id,title,audio,questions:qs.slice(0,10)}
}
const D=[
make("2.1","Separarea teoriei de practică","2_1.m4a",[
["relația teorie–practică","teoria și practica se influențează reciproc",["teoria trebuie izolată de experiență","practica este neutră teoretic","experiența elimină nevoia de reflecție"],"Bush respinge separarea rigidă: practica este interpretată prin cadre teoretice."],
["bunul-simț managerial","conține presupoziții și teorii implicite",["este complet lipsit de teorie","garantează aceeași soluție în orice școală","înlocuiește analiza critică"],"Deciziile aparent evidente au în spate presupoziții ce trebuie făcute explicite."],
["reflecția critică","face vizibile presupozițiile care ghidează decizia",["elimină contextul","transformă teoria în regulă fixă","exclude experiența"],"Reflecția critică leagă experiența de cadre explicative."],
["practica profesională","poate genera, testa și modifica teoria",["doar aplică mecanic teoria","nu produce informații relevante","este identică în toate organizațiile"],"Relația este circulară, nu unidirecțională."]
]),
make("2.2","Relevanța teoriei pentru buna practică","2_2.m4a",[
["experiența personală","este limitată și trebuie completată de perspective mai largi",["este suficientă în orice situație","face inutilă teoria","produce automat decizii transferabile"],"Teoria extinde experiența individuală și ajută la interpretarea contextelor noi."],
["rolul teoriei","oferă modele mentale pentru interpretarea evenimentelor",["prescrie o singură soluție universală","înlocuiește judecata profesională","elimină nevoia de observație"],"Teoria oferă cadre de interpretare, nu rețete universale."],
["transferul practicilor","cere analizarea contextului înainte de aplicare",["este automat între școli","depinde doar de vechimea directorului","nu necesită adaptare"],"Ce funcționează într-o școală poate eșua în alta."],
["decizia argumentată","combină experiența, teoria și analiza contextului",["se bazează exclusiv pe intuiție","ignoră perspectivele altora","repetă mecanic soluțiile anterioare"],"Buna practică presupune interpretare, nu simplă rutină."]
]),
make("2.3","Natura teoriei","2_3.m4a",[
["pluralismul teoretic","acceptă mai multe perspective parțiale asupra organizației",["caută un singur adevăr universal","respinge toate modelele","elimină diferențele de context"],"Niciun model nu explică întreaga organizație."],
["perspectiva","funcționează ca filtru pentru selectarea și interpretarea evenimentelor",["este o regulă juridică","este un indicator financiar","este o procedură fixă"],"House folosește ideea de perspectivă ca filtru interpretativ."],
["metafora organizațională","oferă un mod valoros, dar parțial, de a vedea organizația",["descrie complet realitatea","nu influențează interpretarea","este echivalentă cu organigrama"],"Morgan subliniază utilitatea și caracterul parțial al metaforelor."],
["paradigma","ghidează conștient sau inconștient gândirea",["este doar o tehnică de evaluare","este exclusiv o normă administrativă","nu afectează decizia"],"Paradigma structurează felul în care este înțeleasă realitatea."]
]),
make("2.4","Caracteristicile teoriei","2_4.m4a",[
["caracterul normativ","arată cum ar trebui conduse instituțiile",["descrie doar ce s-a întâmplat","exclude valorile","interzice observația"],"Utilizarea normativă trebuie deosebită de cea descriptivă."],
["caracterul selectiv","evidențiază unele dimensiuni și lasă altele în plan secund",["explică exhaustiv organizația","elimină alegerea perspectivei","produce răspunsuri identice"],"Orice teorie selectează anumite aspecte ale realității."],
["baza empirică","observația poate genera sau testa concepte și teorii",["observația este incompatibilă cu teoria","datele nu pot modifica teoria","cercetarea este inutilă"],"Teoria și observația se pot alimenta reciproc."],
["rezerva modelului subiectiv","observarea externă poate rata sensurile atribuite de participanți",["participanții nu dau sens evenimentelor","doar structura formală contează","interpretarea individuală este irelevantă"],"Sensurile actorilor nu sunt întotdeauna accesibile observatorului extern."]
]),
make("2.5","Diversitatea în leadership și management educațional","2_5.m4a",[
["diversitatea","cere adaptarea teoriilor și practicilor la școli și comunități diferite",["impune un model identic tuturor","elimină contextul cultural","face inutile perspectivele multiple"],"Modelele trebuie analizate în raport cu diversitatea organizațiilor."],
["stereotipurile de leadership","pot crea bariere de acces și promovare",["garantează reprezentarea echilibrată","sunt neutre organizațional","nu influențează selecția"],"Normele dominante pot produce subreprezentare."],
["calitățile de leadership","nu sunt determinate de gen",["aparțin exclusiv unui profil masculin","exclud grija și creativitatea","sunt identice cu autoritatea formală"],"Bush discută depășirea stereotipurilor tradiționale."],
["reprezentarea minorităților","poate fi redusă de stereotipuri și acces inegal la formare",["depinde numai de organigramă","nu este influențată de selecție","este independentă de bariere"],"Accesul și practicile de selecție contează."]
]),
make("2.6","Modele de management educațional: introducere","2_6.m4a",[
["modelele de management","sunt categorii integratoare pentru perspective suprapuse",["sunt rețete obligatorii","se exclud întotdeauna reciproc","descriu doar finanțele"],"Bush grupează literatura în șase modele de management."],
["modelul formal","accentuează structuri, roluri și obiective oficiale",["pune în centru ambiguitatea","elimină autoritatea","se bazează exclusiv pe emoții"],"Formalul este asociat cu structura și controlul managerial."],
["modelul colegial","accentuează participarea și responsabilitatea împărtășită",["presupune decizie exclusiv unilaterală","elimină colaborarea","se bazează doar pe conflict"],"Colegiul și participarea sunt elemente centrale."],
["cele șase modele","sunt formal, colegial, politic, subiectiv, de ambiguitate și cultural",["sunt doar formal și informal","sunt trei modele fixe","sunt exclusiv modele de leadership"],"Aceasta este tipologia integratoare folosită de Bush."]
]),
make("2.7","Modele de leadership educațional: introducere","2_7.m4a",[
["leadershipul managerial","este asociat în principal modelului formal",["este asociat exclusiv ambiguității","respinge structurile","exclude obiectivele oficiale"],"Corespondența de bază este formal–managerial."],
["leadershipul participativ, transformațional și distribuit","se asociază modelului colegial",["se asociază doar birocrației","elimină participarea","sunt forme de control ierarhic pur"],"Aceste forme împart influența și responsabilitatea."],
["leadershipul tranzacțional","se leagă de interese, schimburi și negociere",["exclude orice schimb","este identic cu leadershipul moral","se bazează numai pe simboluri"],"Este asociat modelului politic."],
["leadershipul instruirii","arată direcția influenței spre predare și învățare, nu un singur proces managerial",["aparține exclusiv modelului formal","este doar control administrativ","exclude rezultatele elevilor"],"Bush îl tratează transversal față de modelele de management."]
]),
make("3.1","Modelele structurale","3_1.m4a",[["modelele structurale","pun accent pe structura oficială și relațiile dintre poziții",["ignoră rolurile și pozițiile","pun în centru exclusiv emoțiile","resping diviziunea muncii"],"Structura, rolurile și relațiile oficiale sunt centrale."],["diviziunea muncii","distribuie sarcini și responsabilități între roluri",["elimină specializarea","face inutile pozițiile","înlocuiește obiectivele"],"Specializarea și distribuirea responsabilităților țin de perspectiva structurală."],["organigrama","reprezintă relațiile formale de autoritate și responsabilitate",["descrie complet cultura informală","înlocuiește toate regulile","arată doar rezultatele elevilor"],"Organigrama exprimă arhitectura formală."],["coordonarea","leagă activitățile specializate de obiectivele organizației",["exclude comunicarea","face inutile obiectivele","separă complet departamentele"],"Structura trebuie să permită coordonarea activităților."]]),
make("3.2","Modelele sistemice","3_2.m4a",[["perspectiva sistemică","vede organizația ca ansamblu de elemente interdependente",["exclude mediul extern","reduce școala la organigramă","tratează fiecare parte izolat"],"Componentele sistemului se influențează reciproc."],["interdependența","înseamnă că modificarea unei părți poate influența alte părți",["fiecare compartiment este complet autonom","nu există efecte organizaționale","schimbarea rămâne locală în orice caz"],"Schimbarea unei componente poate afecta întregul sistem."],["intrările și ieșirile","leagă resursele primite de rezultatele produse",["descriu doar ierarhia","elimină procesele interne","sunt concepte fără legătură"],"Modelul sistemic urmărește relația dintre intrări, procese și ieșiri."],["mediul","poate influența funcționarea și rezultatele organizației",["este întotdeauna irelevant","nu poate furniza resurse","rămâne complet separat de școală"],"Perspectiva sistemică analizează și relația organizației cu mediul."]]),
make("3.2.1","Sisteme deschise sau închise","3_2_1.m4a",[["sistemul deschis","interacționează cu mediul extern",["este complet izolat de mediu","nu primește informații din exterior","nu produce rezultate pentru mediu"],"Sistemul deschis realizează schimburi cu mediul."],["sistemul închis","este conceptualizat printr-o relație minimă sau absentă cu mediul",["depinde intens de schimburile externe","este definit prin participare colegială","presupune negociere politică"],"Distincția privește gradul de interacțiune cu mediul."],["școala ca sistem deschis","primește resurse și informații și produce rezultate pentru mediul său",["funcționează fără intrări externe","nu are relații cu comunitatea","produce rezultate fără procese interne"],"Instituția educațională este influențată de contextul extern."],["frontiera sistemului","separă organizația de mediu fără a exclude schimburile",["elimină orice comunicare externă","face mediul irelevant","transformă sistemul în ierarhie"],"Un sistem deschis are granițe, dar permite schimburi."]]),
make("3.3","Modelele birocratice","3_3.m4a",[["birocrația","se bazează pe reguli, ierarhie, specializare și autoritate formală",["elimină regulile","funcționează numai informal","respinge specializarea"],"Regulile, ierarhia și specializarea sunt caracteristice modelului birocratic."],["regulile","urmăresc standardizarea și predictibilitatea activității",["elimină responsabilitatea","fac decizia complet aleatorie","înlocuiesc toate obiectivele"],"Procedurile clarifică așteptările și reduc variația."],["ierarhia birocratică","stabilește niveluri de autoritate și răspundere",["elimină diferențele de poziție","nu definește responsabilități","se bazează exclusiv pe carismă"],"Autoritatea este distribuită pe niveluri."],["specializarea","asociază sarcini distincte unor roluri definite",["elimină diviziunea muncii","exclude expertiza","presupune că toți fac aceleași sarcini"],"Birocrația valorifică diviziunea funcțională."]]),
make("3.3.1","Aplicarea modelului birocratic în educație","3_3_1.m4a",[["aplicarea birocrației în educație","presupune roluri oficiale, reguli și niveluri de autoritate",["elimină procedurile instituționale","exclude responsabilitățile formale","funcționează numai prin relații personale"],"În școli, modelul birocratic se observă în structuri, reguli și responsabilități."],["procedurile școlare","pot standardiza activități și clarifica responsabilități",["fac imposibilă coordonarea","înlocuiesc toate obiectivele educaționale","nu au nicio funcție organizațională"],"Procedurile pot crește predictibilitatea funcționării."],["autoritatea formală în școală","este asociată rolurilor și pozițiilor instituționale",["aparține exclusiv grupurilor informale","este independentă de funcție","provine numai din popularitate"],"Modelul birocratic leagă autoritatea de poziția formală."],["limita aplicării birocratice","apare când regulile și structurile nu surprind întreaga realitate a școlii",["regulile explică orice situație","structura formală include toate relațiile informale","școala funcționează fără context"],"Viața organizațională nu poate fi redusă integral la reguli."]]),
make("3.4","Modelele raționale","3_4.m4a",[["modelul rațional","pornește de la obiective și alegerea mijloacelor adecvate pentru atingerea lor",["decide fără alternative","pune simbolurile înaintea rezultatelor","respinge obiectivele"],"Raționalitatea leagă scopurile de mijloace."],["procesul decizional rațional","compară alternativele în raport cu criterii și obiective",["alege fără criterii","exclude informația","se bazează doar pe rutină"],"Alternativele sunt evaluate sistematic."],["eficacitatea","privește gradul de atingere a obiectivelor",["este identică cu ierarhia","înseamnă doar reducerea costurilor","nu are legătură cu rezultate"],"Eficacitatea se raportează la scopuri."],["limita raționalității","apare când obiectivele sunt neclare sau contestate",["contextul nu contează","obiectivele sunt întotdeauna clare","dispare orice nevoie de analiză"],"Modelele raționale funcționează mai greu în ambiguitate."]]),
make("3.5","Modelele ierarhice","3_5.m4a",[["ierarhia","ordonează pozițiile pe niveluri de autoritate",["descrie doar cultura","elimină autoritatea formală","presupune egalitate totală a rolurilor"],"Ierarhia structurează relațiile verticale."],["responsabilitatea","este asociată poziției și nivelului de autoritate",["aparține exclusiv grupurilor informale","este independentă de rol","nu poate fi atribuită formal"],"Rolurile formale includ răspunderi explicite."],["comunicarea verticală","circulă între nivelurile ierarhice",["este doar externă","exclude conducerea","nu poate transmite decizii"],"Structura ierarhică organizează fluxurile de decizie și raportare."],["directorul în modelul ierarhic","ocupă o poziție centrală de autoritate formală",["este doar observator","nu are atribuții distincte","nu poate coordona"],"Poziția de vârf concentrează responsabilități manageriale."]]),
make("3.6.1","Modelele formale – Obiective","3_6_1.m4a",[["obiectivele formale","oferă criterii oficiale pentru decizie și evaluare",["apar doar informal","nu influențează managementul","sunt întotdeauna irelevante"],"Modelele formale presupun orientarea spre scopuri declarate."],["claritatea obiectivelor","susține evaluarea alternativelor și a rezultatelor",["elimină nevoia de criterii","face imposibilă evaluarea","nu are legătură cu decizia"],"Raționalitatea formală presupune obiective suficient de clare."],["obiectivele organizaționale","orientează activitatea și coordonarea formală",["apar doar după luarea deciziei","exclud responsabilitatea","nu au legătură cu structura"],"Scopurile declarate oferă direcție organizației."],["o limită a obiectivelor formale","este posibilitatea ca ele să fie multiple sau contestate",["sunt întotdeauna acceptate unanim","nu pot fi ambigue","nu diferă între actori"],"În organizațiile educaționale, scopurile pot fi interpretate diferit."]]),
make("3.6.2","Modelele formale – Structura organizațională","3_6_2.m4a",[["structura organizațională","definește roluri, poziții și relații oficiale",["descrie numai emoțiile membrilor","elimină responsabilitatea","este identică cu mediul extern"],"Structura este o dimensiune centrală a modelelor formale."],["rolurile formale","precizează responsabilități și așteptări organizaționale",["sunt complet independente de structură","nu presupun sarcini","înlocuiesc obiectivele"],"Rolurile fac parte din arhitectura formală."],["coordonarea structurală","leagă activitățile diferitelor poziții și compartimente",["elimină comunicarea","exclude specializarea","separă complet activitățile"],"Structura trebuie să permită coordonarea."],["limita structurii formale","este că nu surprinde toate relațiile informale",["descrie exhaustiv cultura","include automat toate interesele","înlocuiește analiza contextului"],"Organigrama nu reprezintă întreaga viață organizațională."]]),
make("3.6.3","Modelele formale – Mediul extern","3_6_3.m4a",[["mediul extern","poate furniza resurse, cerințe și constrângeri organizației",["este complet separat de școală","nu influențează funcționarea","produce doar reguli interne"],"Organizația educațională funcționează într-un context extern."],["relația cu mediul","poate influența structura și deciziile organizației",["este mereu irelevantă","nu produce schimbări","se reduce la organigramă"],"Contextul extern poate modifica priorități și funcționarea."],["resursele externe","pot condiționa posibilitățile de acțiune ale organizației",["nu au efect asupra activității","elimină obiectivele","sunt exclusiv simbolice"],"Resursele și constrângerile externe contează în management."],["adaptarea la mediu","presupune răspuns organizațional la cerințe și schimbări externe",["înseamnă izolarea completă","exclude analiza contextului","face inutile deciziile"],"Organizațiile nu funcționează în vid."]]),
make("3.6.4","Modelele formale – Leadership","3_6_4.m4a",[["leadershipul formal","se sprijină pe poziție, autoritate și responsabilitate managerială",["depinde numai de emoții","exclude rolurile oficiale","nu are legătură cu structura"],"Autoritatea pozițională este centrală în perspectiva formală."],["autoritatea liderului","este asociată rolului oficial ocupat în organizație",["este exclusiv informală","nu implică responsabilitate","provine numai din popularitate"],"Poziția formală conferă autoritate legitimă."],["coordonarea prin leadership","urmărește alinierea activităților cu obiectivele organizației",["elimină obiectivele","exclude responsabilitatea","separă complet activitățile"],"Leadershipul formal susține implementarea scopurilor."],["o limită a leadershipului formal","este că influența nu provine numai din poziția oficială",["poziția explică toate formele de influență","expertiza nu contează niciodată","relațiile informale sunt inexistente"],"Expertiza și relațiile pot produce influență dincolo de funcție."]]),
make("3.7","Leadershipul managerial","3_7.m4a",[["leadershipul managerial","pune accent pe funcții, sarcini și comportamente necesare funcționării organizației",["elimină obiectivele","respinge managementul","se bazează exclusiv pe simboluri"],"Este strâns legat de perspectiva formală."],["autoritatea liderului managerial","derivă în mare măsură din poziția formală",["exclude responsabilitatea","nu are bază organizațională","provine numai din popularitate"],"Poziția oficială susține influența managerială."],["prioritatea managerială","este realizarea eficientă a activităților și obiectivelor stabilite",["este evitarea coordonării","este eliminarea standardelor","este menținerea ambiguității"],"Modelul urmărește implementarea și funcționarea eficientă."],["limita leadershipului managerial","poate supraaccentua structura și sarcinile în detrimentul altor dimensiuni",["explică exhaustiv orice situație","exclude complet managementul","nu are nicio limită"],"Ca orice lentilă, este parțial."]]),
make("3.8","Limitările modelelor formale","3_8.m4a",[["o limită a modelelor formale","este presupunerea că obiectivele organizației sunt clare și acceptate",["accentul pe sensuri individuale","recunoașterea conflictului permanent","respingerea structurii"],"În școli, scopurile pot fi multiple sau contestate."],["structura formală","nu surprinde întreaga viață informală a organizației",["elimină cultura","explică toate relațiile personale","face inutilă analiza puterii"],"Relațiile informale pot modifica funcționarea reală."],["raționalitatea","este limitată de informație incompletă, ambiguitate și interese diferite",["este întotdeauna perfectă","exclude contextul","nu depinde de informații"],"Decizia reală nu urmează mereu modelul ideal."],["autoritatea formală","nu este singura sursă de influență în școală",["elimină expertiza","este unica sursă posibilă","face inutile relațiile"],"Expertiza și relațiile pot produce influență dincolo de poziție."]]),
make("3.9","Concluzie","3_9.m4a",[["validitatea modelelor formale","rămâne importantă, dar depinde de context și trebuie completată de alte perspective",["a dispărut complet","este universală și suficientă singură","exclude pluralismul"],"Bush tratează modelele ca lentile parțiale, nu explicații totale."],["utilitatea structurii","este mare pentru clarificarea rolurilor, responsabilităților și coordonării",["este nulă în școli","elimină nevoia de leadership","înlocuiește cultura"],"Structura formală continuă să aibă funcții reale."],["pluralismul","permite combinarea modelului formal cu alte lentile explicative",["face contextul irelevant","impune o singură teorie","interzice combinarea modelelor"],"Niciun model nu explică singur întreaga organizație."],["alegerea modelului","trebuie raportată la problema și contextul analizat",["depinde doar de tradiție","nu necesită analiză","se face identic în orice situație"],"Contextul decide cât de utilă este fiecare perspectivă."]])
])];
window.MODULES=window.MODULES.concat(D);
})();